#!/usr/bin/env python

import os

api = os.path.abspath("extension_api.json")
ARGUMENTS.setdefault("custom_api_file", api)

env = SConscript("godot-cpp/SConstruct")

env.Append(CPPPATH=["src/", "../sim/include/"])
env.Append(CXXFLAGS=["-std=c++17"])

sources = Glob("src/*.cpp") + Glob("../sim/src/*.cpp") + Glob("../sim/src/*/*.cpp")

libname = "librasim.{}.{}{}".format(env["platform"], env["arch"], env["SHLIBSUFFIX"])
library = env.SharedLibrary(target="../game/bin/" + libname, source=sources)
Default(library)
