tutorial-ui-camera = One finger selects units and gives orders, two fingers pan the camera, three fingers pinch to zoom.
tutorial-ui-statusbar = The bar at the top shows your credits, power balance and storage — watch it as you build.
tutorial-ui-menu = The menu button (top left) pauses, saves, changes game speed and options.
tutorial-ui-music = The music button toggles the soundtrack on and off.
tutorial-obj-deploy = Select your Mobile Construction Vehicle and tap it again to deploy it into a Construction Yard.
tutorial-obj-power = Build a Power Plant.
tutorial-obj-refinery = Build an Ore Refinery — it comes with a free Harvester for the nearby ore.
tutorial-ui-economy = The Harvester brings ore to the refinery and turns it into credits — build Ore Silos for more storage.
tutorial-obj-barracks = Build a Barracks.
tutorial-obj-infantry = Train 3 Riflemen (E1) in the Barracks.
tutorial-obj-group-assign = Select your three riflemen (drag a box around them), then long-press 1 to save them as a group.
tutorial-obj-group-select = Tap 1 to select the saved group again.
tutorial-obj-turret = Build a Pillbox to defend your base.
tutorial-ui-cmdbar-intro = The button row next to the minimap holds ten quick commands — try each one out.
tutorial-ui-cmd-sell = Sell ONLY the Pillbox: tap Sell, then tap the Pillbox.
tutorial-ui-cmd-repair = The Pillbox is damaged. Tap Repair, then tap the Pillbox to heal it automatically.
tutorial-ui-cmd-clear = Tap Clear to deselect everything.
tutorial-ui-cmd-add = Tap a rifleman, then tap Add (extends the selection), and tap more riflemen — the selection should grow.
tutorial-ui-cmd-clear2 = Tap empty ground or Clear again to deselect everything.
tutorial-ui-cmd-all = Tap All — that selects every combat unit; harvesters stay out.
tutorial-ui-cmd-base = Tap Base to jump the camera to your Construction Yard.
tutorial-ui-cmd-event = Alarm jumps to the last thing that needed your attention.
tutorial-ui-cmd-sel = Tap Sel. to jump the camera to your current selection.
tutorial-ui-cmd-zoom = Zoom with three spread fingers or the +/- buttons — change the view now.
tutorial-obj-warfactory = Build a War Factory.
tutorial-obj-tanks = Build 2 Light Tanks (1TNK).
tutorial-ui-superweapons = A superweapon panel would appear here once you build one — none in this tutorial.
tutorial-obj-dome = Build a Radar Dome — it unlocks the radar on the minimap.
tutorial-ui-lowpower = Your power supply is no longer enough — Power now shows red up top, buildings dim, and the radar goes dark.
tutorial-obj-apwr = Build an Advanced Power Plant — it brings your power supply back into balance.
tutorial-ui-minimap = The minimap (bottom left) now shows your base. Tap it to jump the camera there; it pings when you're attacked.
tutorial-ui-radial-unit = Long-press a unit to open its radial menu: Attack, Force Fire, Guard, Scatter, Stop, Rally.
tutorial-ui-radial-building = Long-press a building for its radial menu: Repair, Primary, Sell, Rally Point.
tutorial-ui-infocard = Long-press an enemy unit or building to see its info card.
tutorial-ui-selection-gestures = Double-tap a unit to select every unit of that type on screen; drag a box to select an area.
tutorial-ui-attackmove = A tap on open ground is a plain move; for an attack-move (fights back along the way) pick "Attack Move" from a unit's radial menu.
tutorial-obj-defend = A small enemy force is attacking! Select your units and defend your base.
tutorial-obj-attack = Long-press near the enemy base and choose Attack to destroy it.
tutorial-side-repair = Side objective: repair a damaged building.
tutorial-side-sell = Side objective: sell a building.
tutorial-hint-openbar = First open the build menu (crane-hook button, bottom right).
tutorial-hint-switchtab = Switch to the matching build menu tab.
tutorial-hint-place = Place the building near your base — green means allowed. Tap it again to construct.
